apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer # Expose the service externally
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
